### ISSUE TITLE
Update CMS project name from 'W3C CMS' to 'W3C'

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#359] opened 2023-06-07 21:12 UTC
The meta elements on pages generated by the CMS (for example [Media kit](https://beta.w3.org/about/press-media/)) include a couple with 'W3C CMS' in the title:

```html
<meta property="og:title" content="Press and media - W3C CMS"/>
<meta name="twitter:title" content="Press and media - W3C CMS"/>
```

These should be 'W3C' instead of 'W3C CMS'.

I think this comes from `$project_name` in [deploy.php](https://github.com/w3c/w3c-website-craft/blob/main/deploy.php).

**Comment by vivienlacourba** [comment] 2023-06-08 11:24
Duplicate of #340

**Closed as completed by vivienlacourba** 2023-06-08 11:24 UTC
Labels: cms
