### ISSUE TITLE
Main menu disappears after using “Make text bigger” option in desktop Safari

### ISSUE THREAD

**Issue by simevidas** [w3c/w3c-website#379] opened 2023-06-20 16:10 UTC
Steps to reproduce:

1. Use Safari on macOS
2. Navigate to https://www.w3.org/
3. Press [Command] [Option] [+]

Notice how the main menu disappears in this video:

https://github.com/w3c/w3c-website/assets/716405/66ea9401-f585-4925-9de0-5234e2605ff2

**Comment by NicolaSaunders** [comment] 2023-06-21 18:08
I would like to test this again after [PR#103](https://github.com/w3c/w3c-website-templates-bundle/pull/103) has been approved and deployed, just in case this changes anything

**Comment by deniak** [comment] 2023-06-22 07:21
Closing as I cannot reproduce this bug after merging https://github.com/w3c/w3c-website-templates-bundle/pull/103.

**Closed by deniak** 2023-06-22 07:21 UTC
Labels: bug, website

**Comment by simevidas** [comment] 2023-06-22 14:14
@deniak Have you not noticed that the menu still does not render correctly in Safari in the same scenario? I’ve created a followup issue here: https://github.com/w3c/w3c-website/issues/389
