### ISSUE TITLE
Form Elements – Buttons Have Inconsistent Selected State

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#1] opened 2021-07-08 09:21 UTC
Raised by Zoonou as part of their accessibility browser and device testing: 

Original issue:
The user observes that the ‘Submit’ and ‘Search’ CTAs remain blue and have black text when selected or focused with the keyboard on macOS Safari. This is inconsistent with the selected state observed on other browsers, such as Chrome and Firefox, where the CTA turns yellow with black copy and a black outline when selected. Please see the attached supporting material for comparison. It is expected that CTAs have a consistent selected/focused state across browsers.

This issue is also observed on the ‘Show results’ CTA on the ‘Listing page: posts (blog, news, press release, in the media)’ page - Posts | W3C Redesign Prototypes  and is believed to be present wherever CTAs with the blue and white formatting are present across all components under test.

It is noted that on Safari on the iPhone 12 Pro, the CTAs have no selected state.

Steps to recreate:
1. Go to URL: https://w3c-dev.studio24.dev/forms.html
2. Scroll down to the foot of the page.
3. Select the ‘Submit’ and ‘Search’ CTAs.
4. Observe the selected state with black copy.
5. Repeat steps 1-3 on another browser, such as Chrome.
6. Observe the yellow and black selected state.

Environment:
Reported against:
macOS 10.15 – Safari 13

This issue is known to occur on:
macOS 10.15 – Safari 13
iPhone 8 - iOS 14.5.1 - Chrome 90
iPhone 12 Pro - iOS 14.5.1 - Safari 14

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.  

Supporting material:
Video and gif

Version:
27/05/2021 - https://w3c-dev.studio24.dev/

Severity:
4. Cosmetic Issue/Typo 

--

Subsequent observation:

It is observed by the user that the CTAs remain the same within the Safari environment when testing on iOS devices where the CTAs remain the colour blue when selected as described within the original ticket, Chrome within iOS functions as expected where the selected state of the CTA is the colour Yellow. (Please the the attached videos for further details)

Issue verified as partially fixed - 24/06/2021

Version: Index | W3C Redesign Prototypes 

Issue is known to occur on:

iPhone 8 - iOS 13.7 - Safari 13
iPad 9.7 (6th gen) - iOS 14.6 - Safari 14

**Comment by NicolaSaunders** [comment] 2021-07-08 13:22
The MacOS issue appears to be resolved in Safari v14. In Safari v13 the active state does appear briefly but appears to be overridden almost instantaneously by the hover state if the pointer is still over the button. Overall this feels like a minor issue.

I have been unable to reproduce the iOS issues (using Browserstack), but again this seems like a minor cosmetic issue.

**Closed by NicolaSaunders** 2021-07-08 13:22 UTC
Labels: bug, wontfix
