### ISSUE TITLE
Font rendering glitches due to fontfaceobserver.js

### ISSUE THREAD

**Issue by bramus** [w3c/w3c-website#24] opened 2021-09-16 19:49 UTC
Seen while using the standard out-of-the-box Chrome, even after repeated loads with a hot cache:

https://user-images.githubusercontent.com/213073/133676163-5f91f342-1446-4175-b879-6257865d3672.mp4

It's the `fontfaceobserver.js` that's the culprit here. Blocking requests to it, makes the UI stable _(but rendered in another font)_.

Is there a specific reason why this JS file is required to change the fonts?

**Comment by gosko** [comment] 2021-09-29 15:31
This issue is present in the [web site prototypes](https://w3c-dev.studio24.dev/) as well, not only on the design system site.

If this happened only the first time our site is visited it might be OK (though undesirable) but it seems to happen every time a page is loaded, even with a hot cache as noted by @bramus.

The filmstrip view of [webpagetest.org](https://www.webpagetest.org/) can be used to confirm the issue, for example on the [business ecosystem page](https://w3c-dev.studio24.dev/business/index.html):


https://user-images.githubusercontent.com/7144396/135300670-dabe8b24-367e-423e-9e62-41140beb3094.mp4

**Comment by NicolaSaunders** [comment] 2022-01-18 14:05
[Font Face Observer ](https://fontfaceobserver.com/) is used to optimise font loading and prevent a flash of invisible text (FOIT) while the browser waits for the custom web font to load.

[How We Load Web Fonts Progressively](https://www.filamentgroup.com/lab/font-events.html) discusses using a Server Side Include(SSI) to apply the `fonts-loaded` class to `html` for optimising return visits where the font will likely have been cached.

Who is best placed to know whether this is possible?

**Comment by gosko** [comment] 2022-01-28 23:51
Hi @NicolaSaunders, after way too much time spent reading about web fonts (which are way more complex than I could have imagined!) I think I found the source of this issue: the .woff2 files served by https://w3c-dev.studio24.dev/ (for example [notosans-regular.woff2](https://w3c-dev.studio24.dev/dist/assets/fonts/notosans/notosans-regular.woff2)) as well as our other sites in development like https://www-staging.w3.org/ are served as application/octet-stream, which seems to impact how they are cached.

I just fixed this manually for the four .woff2 files in this directory https://cdn-staging.w3.org/assets/website-2021/fonts/notosans/ and this seems to have resolved the issue on https://www-staging.w3.org/ . I will raise an issue with our team to make sure .woff2 and other files get added to our CDN using the correct mime types.

There is one issue remaining on www-staging that I think would be worth addressing: whenever browsing between pages, the nav menu has a quick flash between its initial appearance and the subsequent javascript adjustment that adds the collapsible submenus including chevrons.

![Screenshot showing nav menu flash](https://user-images.githubusercontent.com/7144396/151634919-9e725440-86e1-4fec-b3ad-3e96e48b5e40.gif)

One potential fix for this might be to update the initial CSS to reserve enough space for the chevrons, so the menu items don't jump around as much after the js has loaded. If someone has js disabled, there would just be a little extra whitespace after each menu item.

![Screenshot showing adjusted menu](https://user-images.githubusercontent.com/7144396/151634939-d6c73a57-2059-477f-af2e-b2f76c2fe364.gif)

For my quick mockup above I added the following to `.global-nav__inner .top-nav-item`:
```
margin-right: 1.7em;
letter-spacing: 0.4px;
line-height: 2;
```
But I'm sure there are better ways to handle this, and I imagine results may vary depending on the user's system fonts.

This seems a bit nitpicky but I find it quite distracting for the menus to jump around whenever a page is loaded so it would be good to resolve this if we can.

**Comment by JuliaSang** [comment] 2022-01-31 13:45
@gosko  

We agree this isn't ideal, thank you for all the research so far. I'm not sure if you are aware, but we're currently looking to fix issues which are either stopping content entry, or are obvious spacing issues that we want to resolve before the final round of external compatibility testing. 

So for the moment we will focus on the high priority issues and, once we've got a list of other issues back from testing, we can prioritise the order to fix those together with this one. I hope that's OK. 

Cheers
Julia

cc / @vivienlacourba

**Comment by gosko** [comment] 2022-01-31 17:27
Hi @JuliaSang, yes, understood. I just wanted to respond to @NicolaSaunders and update the issue with what I learned (also so I could close the million font-related browser tabs I had open.) I understand this will need to be prioritized along with everything else.

**Comment by NicolaSaunders** [comment] 2022-02-01 10:06
Thanks for the update and sleuthing @gosko 

I think it's also worth adding `font-display: fallback` to the `@font-face` declarations (cc @maries24 )

**Comment by NicolaSaunders** [comment] 2023-06-19 13:58
I have added a fix to minimise the horizontal jump in navigation items, caused by the appearance of the chevron, as part of the branch [hotfix/refactor-global-nav](https://github.com/w3c/w3c-website-templates-bundle/tree/hotfix/refactor-global-nav).

I have chosen to include the SVG icon in the initial link markup and hide it using `visibility: hidden` rather than adding the icon when converting the links to buttons. This hides the icon but reserves the space that it occupies. This style is removed when the JavaScript converts the links to buttons.

**Comment by deniak** [comment] 2023-06-22 07:17
Fixed by https://github.com/w3c/w3c-website-templates-bundle/pull/103

**Closed by deniak** 2023-06-22 07:17 UTC
Labels: bug, design system, website
