### ISSUE TITLE
[calendar] bring back colored status tags

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#399] opened 2023-06-27 22:19 UTC
**Describe the issue**
The old calendar had colors for calendar event status tags, and that was kinda nice.

**To reproduce**
Load the [secret magic calendar URL](https://github.com/w3c/w3c-website/issues/313).

**Expected behavior**
Expected: Tentative/Confirmed/Cancelled/Upcoming/Etc are colored.
Actual: Everything is gray.

**Comment by NicolaSaunders** [comment] 2023-07-18 10:28
I have been assigned to this task, but I am not familiar with how the calendar used to look, what colours were used for which event status types, etc.

Could somebody provide me with more details please? Is there an archive of the calendar anywhere that I could take a look at, perhaps via [Internet Archive](https://archive.org/web/)?

I'm also pondering the accessibility of using colour in this way - was there any other indication of event status with the old calendar?

**Comment by jean-gui** [comment] 2023-07-18 12:17
@NicolaSaunders Here are some screenshots of colored status tags:
![tags1](https://github.com/w3c/w3c-website/assets/1479073/997cb635-85be-4827-b697-7980e33a1c64)
![tags2](https://github.com/w3c/w3c-website/assets/1479073/c1e0b4bf-a873-4a28-bf02-4539d90e52a7)
![tags3](https://github.com/w3c/w3c-website/assets/1479073/6248124f-a7aa-45f5-8c86-a91b013db27d)

We are using tags to indicate different statuses:
* draft/tentative/confirmed/canceled
* past/upcoming/in-progress
* category (group meetings/breakout sessions)

Those tags had different colors (based on [bootstrap colors](https://getbootstrap.com/docs/4.6/components/badge/#contextual-variations) to be more visually identifiable but we've lost that with the redesign.

It should be fairly easy to create new classes and use the [color palette](https://design-system.w3.org/settings/#color-palette).

I'm wondering whether we should:
1) create classes specific to events (.tag-event-confirmed, .tag-event-upcoming, ...)
2) create classes specific to tags (.tag-green, .tag-blue, ...)
3) create generic classes to set a color and background-color (.color-green, .color-blue, ...)

For options 2 and 3 I also wonder whether we should be exhaustive, and use some SASS code to generate those classes for all colors in the palette, or if we should only do a few.

**Comment by NicolaSaunders** [comment] 2023-07-18 13:19
Thanks for the clarification @jean-gui 

Please disregard my earlier comment about accessibility - I had not picked up that the colouring is used within textual tags.

**Comment by NicolaSaunders** [comment] 2023-07-19 09:15
I feel that this may need some design input, so I am checking internally on this before proceeding.

**Comment by NicolaSaunders** [comment] 2023-07-21 16:07
Here is a screenshot illustrating proposed changes for tag styles from our designer:
![Screenshot of proposed styles for event tags](https://github.com/w3c/w3c-website/assets/31240259/7e42b577-ec03-45ca-b110-fbcad720f9c3)
Please ignore everything apart from the colour changes, which can be summarised as follows:

- Past: keep current tag colouring (background colour `#cecdcd` with 80% opacity, text colour `#111111`)
- Up-coming / in-progress: set background colour to `#fc7750`
- Tentative / confirmed / draft / cancelled: set background colour to `#ffffff` and add a solid border using the text colour `#111111`
- Group meetings / breakout sessions: set background colour to `#920ba6` and text colour to `#ffffff`

He doesn't recommend recommend adding separate colours for each possible type of tag (9 in total), as it's too much for a user to learn. If tags are important perhaps there should be filters for these options?

**Comment by jean-gui** [comment] 2023-07-24 07:18
I'm not sure that using  the same colors for the status (draft, tentative, confirmed, cancelled) is great: having different colors allows one to quickly find out which meetings they should pay attention to. Similarly, using different colors for upcoming and in-progress allows to quickly see if you need to join a meeting.

Filters would work for these, but they need more clicks to get to the information, so I tend to see them as a complementary feature to the colors, rather than a replacement.

@fantasai What are your thoughts about that?

**Comment by NicolaSaunders** [comment] 2023-08-07 17:28
@jean-gui @fantasai How about if the past, tentative/draft, and in-progress tags used the suggested colour combinations and we add new combinations for:

- upcoming/confirmed: set background colour to `#046704` and text colour to `#ffffff`
- cancelled: set background colour to `#a82615` and text colour to `#ffffff`

Might that work better?

As for how best to name the CSS classes, while I appreciate your point of view with options 2 and 3, I recommend semantic names for clarity and maintainability.

I see there is a Sass partial in `90-utilities` for handling text/border colours. We also have an unused Sass partial in `30-base` (it's not imported in `core.scss `or `advanced.scss`) intended for custom background/foreground colour combinations.

We could potentially combine and rationalise this somewhat in that colour utilities file, with two named utility classes:

- one for border/font colour
- one for background/font colour

It could work something like:
```
.u-bg-error {
    background-color: $error-color;
    color: $white;
}

.u-color-error {
    border-color: $error-color;
    color : $error-color;
}


.u-bg-info {
    background-color: $info-color;
    color: $white;
}

.u-color-info {
    border-color: $info-color;
    color : $info-color;
}


.u-bg-success {
    background-color: $success-color;
    color: $white;
}

.u-color-success {
    border-color: $success-color;
    color : $success-color;
}


.u-bg-warning {
    background-color: $warning-color;
    color: $off-black;
}

.u-color-warning {
    border-color: $success-color;
    color : $off-black;
}
```

The naming is based on some of the Sass variables already in use. Tags for the upcoming/confirmed status could map to `.u-bg-success` and those for the cancelled status could map to `.u-bg-error`. The tentative/draft status tags could map to a new class of `.u-color-draft` and the in-progress status could map to a new class of `.u-color-active` or `.u-color-in-progress`, and so on.

On the tags themselves we should only have to add the relevant utility class to override the starting styles.

**Comment by jean-gui** [comment] 2023-08-08 14:28
@NicolaSaunders Your proposed colors look ok to me. As for class names and Sass, I'll let you be the judge for what's best to use as this is not my area of expertise.

**Comment by vivienlacourba** [comment] 2023-09-20 09:17
@NicolaSaunders will create a PR.

**Comment by NicolaSaunders** [comment] 2023-09-20 17:34
Proposed fix at https://github.com/w3c/w3c-website-templates-bundle/pull/122

**Comment by jean-gui** [comment] 2023-11-21 11:11
I've merged and deployed. See https://www.w3.org/events/meetings/4a527bc3-c83d-408e-b978-307dca9999fc/ for example.

**Closed by jean-gui** 2023-11-21 11:11 UTC
Labels: design system, website
